export default {
  COLORS: {
    GRADIENT_SPLASH_BG: ['#6F85DF', '#1B077F'],
    GRADIENT_CARD: ['#1B077F', '#6F85DF'],
    GRADIENT_CARD_SERIE: ['#EEF0FF', '#FFFBFE'],
    GRADIENT_BUTTON: ['#FFD44D', '#FF230A'],
    GRADIENT_TEXT: ['#FFD54D', '#FF1911'],
    GRADIENT_HEADER_50PERCENT: ['#6F85DF', '#1B077F'],

    TEXT_LIGHT: '#FFD54D',

    NEUTRA_BACKGROUND: '#ECECF2',
    NEUTRA_LETTER_AND_STROKE: '#F0F2F2',
    NEUTRA_PLACEHOLDER: '#202020',
    NEUTRA_CARD_BALL_BG: '#E1E5ED',
    NEUTRA_BLACK_LOGO: '#262626',

    BLUE_STROKE: '#1B077F',
    BLUE_INACTIVE_STROKE: '#9D8BF9',
    BLUE_RADIAL_LOGO_EFFECT: '#81AFF8',
    BLUE_CARD_CONFIRM_BUTTON: '#81AFF8',
    BLUE_NOTIFICATION_BG_20PERCENT: '#3863FF',

    AUX_GOOGLE_RED: '#D92727',
    AUX_GOOGLE_GREEN: '#1CAA44',
    AUX_GOOGLE_BLUE: '#3863FF',
    AUX_GOOGLE_YELLOW: '#FBBC05',
    AUX_WHATSAPP: '#25D366',
  },

  FONTS: {
    BUTTON: 'Inter_700Bold',
    H1: 'RobotoSlab_700Bold',
    BODY: 'Inter_400Regular',
    SUBTITLE: 'RobotoSlab_500Medium',
  },
}
